// PAGE ITEMS
export const PAGE_STATE_HOME = 'PAGE_STATE_HOME';
export const PAGE_STATE_SIGN_UP = 'PAGE_STATE_SIGN_UP';
export const PAGE_STATE_DASH_BOARD = 'PAGE_STATE_DASH_BOARD';

// UPDATE STATE
export const UPDATE_PAGE_STATE = 'UPDATE_PAGE_STATE';
